# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tornado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tornado_id', models.PositiveIntegerField()),
                ('rotation', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance_covered', models.CharField(max_length=25)),
                ('fujita_scale_rating', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TornadoDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('deaths', models.PositiveIntegerField()),
                ('bridges', models.PositiveIntegerField()),
                ('houses', models.PositiveIntegerField()),
                ('tornado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tornado.Tornado')),
            ],
        ),
    ]
