# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tornado',
            name='fujita_scale_rating',
            field=models.CharField(choices=[('F0', 'Light damage'), ('F1', 'Moderate damage'), ('F2', 'Considerable damage'), ('F3', 'Severe damage'), ('F4', 'Devastating damage'), ('F5', 'Incredible damage')], max_length=256),
        ),
    ]
