# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornado', '0002_auto_20190413_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tornadodamage',
            old_name='houses',
            new_name='house_destroyed',
        ),
        migrations.AlterField(
            model_name='tornadodamage',
            name='bridges',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
