# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquakedamage',
            name='earthquake_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='true', serialize=False, to='etv.Earthquake'),
        ),
        migrations.AlterField(
            model_name='tsunamidamage',
            name='tsunami_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='true', serialize=False, to='etv.Tsunami'),
        ),
        migrations.AlterField(
            model_name='volcanodamage',
            name='volcano_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='true', serialize=False, to='etv.VolcanicEruption'),
        ),
    ]
