# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0002_auto_20190330_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earthquake',
            name='location',
        ),
    ]
