# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0004_auto_20190331_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsunami',
            name='country',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='tsunami',
            name='place',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
