# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0005_auto_20190409_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuakeTsunami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earthquake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etv.Earthquake')),
                ('tsunami_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etv.Tsunami')),
            ],
        ),
        migrations.CreateModel(
            name='VolcanoTsunami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsunami_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etv.Tsunami')),
                ('volcano_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etv.VolcanicEruption')),
            ],
        ),
    ]
