# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etv', '0008_auto_20190413_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquakedamage',
            name='bridges_destroyed',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tsunamidamage',
            name='bridge_destroyed',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
